### PR TITLE
Temporary Fix

### PR DESCRIPTION
**Pull request by ghost1372**
temporary fix

### CODE REVIEW

**Comment by NotYoojun** [comment]
So you just use the CombinedResource as a merged dictionary in the other dictionaries. I don't think this is a good solution cause it will make the CombinedResources loaded multiple times.

**Comment by ghost1372** [comment]
> So you just use the CombinedResource as a merged dictionary in the other dictionaries. I don't think this is a good solution cause it will make the CombinedResources loaded multiple times.

Yes this is not a good idea, i wonder why referencing single style not working.

With this condition, you have 2 ways, either ignore this feature and revert the commits.
Or merge both libraries into one library.
I try to implement the second way to see its effects.

I am sorry for what happened

**Comment by NotYoojun** [comment]
What about applying XAMLTools to the **iNKORE.UI.WPF.Modern.Controls** library?

**Comment by ghost1372** [comment]
> What about applying XAMLTools to the **iNKORE.UI.WPF.Modern.Controls** library?

It should work, I will test as soon as I get home

**Comment by ghost1372** [comment]
> What about applying XAMLTools to the **iNKORE.UI.WPF.Modern.Controls** library?

You mean we use XamlTools only for **iNKORE.UI.WPF.Modern.Controls** and not **iNKORE.UI.WPF.Modern** ??
Or you mean XamlTools for  both? Because i tested for both and not working.

**Comment by NotYoojun** [comment]
I mean for both.
If that still happens, I guess I have to revert those changes 😭😭

**Comment by ghost1372** [comment]
> I mean for both.
> If that still happens, I guess I have to revert those changes 😭😭

Yes unfortunately

**Pull request closed without merging**
