### PR TITLE
Merge resources/part1

### LINKED ISSUE #22: Improve Performance and Simplify Xaml Resources
we can improve Performance and simplify Xaml Resources, I did this for HandyControl and it can improves performance and simplify development and xaml resources.
in WPF We must have only one resource file (containing all resources a single very very large file), otherwise we will suffer from performance loss.  Since it is very difficult to develop the app in only one xaml file, we use MergedDictionary and seperated files.
But what if we use separate files but collect them all in one file? In this case, we have made the development process easier and improved the performance.

we can use a tool called: **XAMLTools.MSBuild**
if you want I can do this and collect all the resources in one file. for this we need to move xaml files in one places, so project structure will be change
let me know if you are agree or not

### PR DESCRIPTION
**Pull request by ghost1372**
Fix #22 
This PR only covers the **iNKORE.UI.WPF.Modern** and **iNKORE.UI.WPF.Modern.Controls** will be done in next pr.

i used a tool called **XAMLTools.MSBuild**  which, Combines multiple XAML files to one large file.
This is useful when you want to provide one Generic.xaml instead of multiple small XAML files.
Using one large XAML file not only makes it easier to consume, but can also drastically improving loading performance.

Things that have been done in this PR:

#### XamlControlsResources.cs file updated to `Theme.xaml` file instead of `ControlsResources.xaml` file.

### CODE REVIEW

**Comment by NotYoojun** [comment]
Wait a minute, did you just put all the control styles in ONE XAML FILE??

**Comment by NotYoojun** [comment]
Hi! I got the following exception when I try to run the sample app:
image

By the way can you change the name `Themes/Theme.xaml` to `Themes/CombinedResources.xaml`? I don't think the name Theme.xaml have a clear meaning.

**Comment by ghost1372** [comment]
> Hi! I got the following exception when I try to run the sample app:
> image
> 
> By the way can you change the name `Themes/Theme.xaml` to `Themes/CombinedResources.xaml`? I don't think the name Theme.xaml have a clear meaning.
> Also, you may have to apply #28 to this pull.

Sure, wait for it

**Comment by NotYoojun** [comment]
image
There's another issue. Go to the Text -> TextBox on the sample app, then right click any textbox, the exception above will throw.
Do you have a minute to solve that?

**Comment by ghost1372** [comment]
> image There's another issue. Go to the Text -> TextBox on the sample app, then right click any textbox, the exception above will throw. Do you have a minute to solve that?

i am working on it

**Comment by ghost1372** [comment]
@NotYoojun  go to Main branch and test it again, this bug still exist and does not related to this pr.

**Comment by ghost1372** [comment]
> OK, i fixed the TextBox issue and made a commit.

excelent, thank you.
when you re-organize second library, i will be ready for second part.
also what do you think, we remove CombinedResources and we just use Generic.xaml?

**Comment by NotYoojun** [comment]
Good idea, maybe you can have a try!

**Comment by NotYoojun** [comment]
Wait a minute, I don't think this is a good action. You see, in XamlControlResources.cs there are some lines like this:
Generic.xaml will be loaded automatically by the WPF mechanics, while the CombinedResources.xaml will be loaded manually when user used XamlControlResources.

If you put them together, All the unnecessary stuff in Generic.xaml will be loaded twice. So I think it's better to keep the current structure. What do you think?

```csharp
        internal static ResourceDictionary ControlsResources
        {
            get
            {
                if (_controlsResources == null)
                {
                    _controlsResources = new ResourceDictionary { Source = PackUriHelper.GetAbsoluteUri("Themes/CombinedResources.xaml") };
                }
                return _controlsResources;
            }
        }

```

> > OK, i fixed the TextBox issue and made a commit.
> 
> excelent, thank you. when you re-organize second library, i will be ready for second part. also what do you think, we remove CombinedResources and we just use Generic.xaml?

**Comment by ghost1372** [comment]
> Wait a minute, I don't think this is a good action. You see, in XamlControlResources.cs there are some lines like this: Generic.xaml will be loaded automatically by the WPF mechanics, while the CombinedResources.xaml will be loaded manually when user used XamlControlResources.
> 
> If you put them together, All the unnecessary stuff in Generic.xaml will be loaded twice. So I think it's better to keep the current structure. What do you think?
> 
> ```cs
>         internal static ResourceDictionary ControlsResources
>         {
>             get
>             {
>                 if (_controlsResources == null)
>                 {
>                     _controlsResources = new ResourceDictionary { Source = PackUriHelper.GetAbsoluteUri("Themes/CombinedResources.xaml") };
>                 }
>                 return _controlsResources;
>             }
>         }
> ```
> 
> > > OK, i fixed the TextBox issue and made a commit.
> > 
> > 
> > excelent, thank you. when you re-organize second library, i will be ready for second part. also what do you think, we remove CombinedResources and we just use Generic.xaml?

let me test and see what is happening

**Pull request merged**
